//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ.Inf.InventoryValidation.Win.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PJ.Inf.InventoryValidation.Win.Resources.SystemMessages", typeof(SystemMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea confirmar la información de inventario.
        /// </summary>
        internal static string MensajeConfirmarInformacion {
            get {
                return ResourceManager.GetString("MensajeConfirmarInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento ya fue inventariado.
        /// </summary>
        internal static string MensajeElementoInventariado {
            get {
                return ResourceManager.GetString("MensajeElementoInventariado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El bien patrimonial a sido reportado para su revisión.
        /// </summary>
        internal static string MensajeElementoObservado {
            get {
                return ResourceManager.GetString("MensajeElementoObservado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email enviado correctamente.
        /// </summary>
        internal static string MensajeEmailEnviado {
            get {
                return ResourceManager.GetString("MensajeEmailEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el bien buscado.
        /// </summary>
        internal static string MensajeExisteBien {
            get {
                return ResourceManager.GetString("MensajeExisteBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un bien con la serie consignada.
        /// </summary>
        internal static string MensajeExisteSerie {
            get {
                return ResourceManager.GetString("MensajeExisteSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea reportar este bien patrimonial, que no coincide con el observado.
        /// </summary>
        internal static string MensajeNoCoincidenciaBienPatrimonial {
            get {
                return ResourceManager.GetString("MensajeNoCoincidenciaBienPatrimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sede del bien encontrado y del trabajador son diferentes.
        /// </summary>
        internal static string MensajeSedeDiferente {
            get {
                return ResourceManager.GetString("MensajeSedeDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una dependencia judicial.
        /// </summary>
        internal static string MensajeSeleccionaDependencia {
            get {
                return ResourceManager.GetString("MensajeSeleccionaDependencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una oficina.
        /// </summary>
        internal static string MensajeSeleccionaOficina {
            get {
                return ResourceManager.GetString("MensajeSeleccionaOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asigne un trabajador al bien.
        /// </summary>
        internal static string MensajeSeleccionaTrabajador {
            get {
                return ResourceManager.GetString("MensajeSeleccionaTrabajador", resourceCulture);
            }
        }
    }
}
